[build]
  command = "npm run build"
  publish = "dist"
  node_version = "18.18.2"

[build.environment]
  NODE_VERSION = "18.18.2"
  NODE_ENV = "production"
  NPM_FLAGS = "--no-optional"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    enable = false 