[build]
  # No build command needed - just publish the static files
  publish = "."

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 

[dev]
  command = "npm run start"
  framework = "#custom" 